export const metadata = {
    title: "Đăng nhập cửa hàng Becky",
    description: "Generated by create next app",
  };
export default function Login() {
    return (
      <>
      
  
  <div class="box">
      <div class="login-box">
          <div class="login-auth__login">
              <div class="login-title">Đăng Nhập</div>
          </div>
          <form action class="login-form">
              <input id="email" name="email" type="text"
                  placeholder="Email " /> <br />
              <input id="pass" name="pass" type="password"
                  placeholder="Mật khẩu " /> <br />
              <div class="login-button">
                  <input class="bnt-cart-right" type="button"
                      value="Đăng Nhập" onclick="login()"/>
              </div>
          </form>
          <p>Chưa có tài khoản đăng ký <a
                  href="/dangky">tại đây</a></p>
      </div>
  </div>
      </>
    );
  }
  