export const metadata = {
  title: "Đăng ký tài khoản",
  description: "Generated by create next app",
};
export default function Register() {
    return (
      <>
      <div class="container">
      <div class="box">
        <div class="login-box">
          <div class="login-auth__login">
            <div class="login-title">ĐĂNG KÝ</div>
          </div>
          <form class="login-form">
            <input id="name" type="text" placeholder="Tên tài khoản" />
            <br />
            <input id="email" type="text" placeholder="Email" />
            <br />
            <input id="phone" type="text" placeholder="Số điện thoại" />
            <br />
            <input id="pass" type="password" placeholder="Mật khẩu" />
            <br />
            <div class="login-button">
              <input class="btn-cart-right" type="button" value="Đăng Ký"
                />
            </div>
          </form>
        </div>
      </div>
    </div>
      </>
    );
  }
  